#' Calculate Ozkan's pTO Using the Original Excel Macro Formula
#'
#' Computes pTO using the weighting scheme from the original Ozkan
#' Excel macro (TD_OMD). This differs from [ozkan_pto()] in how
#' slicing steps are weighted: the macro uses only the number of
#' "active" steps (steps where >= 2 species survive) rather than
#' n_s = max_abundance as described in the published paper.
#'
#' @param community A named numeric vector of species abundances.
#'   Names must match the first column of `tax_tree`.
#' @param tax_tree A data frame with taxonomic hierarchy. First column
#'   is species names, subsequent columns are taxonomic ranks from
#'   lowest to highest (e.g., Species, Genus, Family, Order, Class,
#'   Phylum, Kingdom).
#'
#' @return A named list with components:
#'   \describe{
#'     \item{uTO}{Unweighted taxonomic diversity (macro formula)}
#'     \item{TO}{Weighted taxonomic diversity (macro formula)}
#'     \item{uTO_plus}{Unweighted taxonomic distance (same as paper)}
#'     \item{TO_plus}{Weighted taxonomic distance (same as paper)}
#'     \item{Ed_levels}{Deng entropy at each taxonomic level (nk=0 slice)}
#'   }
#'
#' @details
#' The Excel macro (TD_OMD, Ozkan 2018a) counts the number of slicing
#' steps where the Deng entropy product is non-zero (\code{n_active}),
#' then assigns weights \code{n_active, n_active-1, ..., 1} to those
#' steps only. Steps where <= 1 species survive are excluded entirely.
#'
#' In contrast, [ozkan_pto()] follows the published formula (Ozkan 2018,
#' Eq. 4) which uses \code{n_s = max_abundance} for all steps, including
#' single-species steps (with product = 1 by the postulation rule).
#'
#' The two functions give identical results when all slicing steps have
#' >= 2 surviving species (\code{n_active == n_s}). They differ when
#' some steps reduce to <= 1 species, which typically occurs in
#' species-poor or abundance-skewed communities.
#'
#' This function is provided for backward compatibility with results
#' generated by the original Excel macro. For new analyses, use
#' [ozkan_pto()] which implements the published formula.
#'
#' @note Maximum 9 slicing steps, matching the Westhoff & van der Maarel
#'   (1973) abundance scale used in the original macro.
#'
#' @references
#' Ozkan, K. (2018). A new proposed measure for estimating taxonomic
#' diversity. Turkish Journal of Forestry, 19(4), 336-346.
#' DOI: 10.18182/tjf.441061
#'
#' @seealso [ozkan_pto()] for the published paper formula,
#'   [deng_entropy_level()] for the core Deng entropy calculation.
#'
#' @examples
#' comm <- c(sp1 = 4, sp2 = 2, sp3 = 3, sp4 = 1, sp5 = 2)
#' tax <- data.frame(
#'   Species = paste0("sp", 1:5),
#'   Genus   = c("G1", "G1", "G1", "G2", "G2"),
#'   Family  = c("F1", "F1", "F1", "F1", "F1"),
#'   stringsAsFactors = FALSE
#' )
#' ozkan_pto_macro(comm, tax)
#'
#' @export
ozkan_pto_macro <- function(community, tax_tree) {
  # --- Input validation ---
  if (!is.numeric(community) || any(community < 0)) {
    stop("'community' must be a numeric vector with non-negative values.",
         call. = FALSE)
  }
  if (is.null(names(community))) {
    stop("'community' must be a named vector.", call. = FALSE)
  }
  if (!is.data.frame(tax_tree)) {
    stop("'tax_tree' must be a data frame.", call. = FALSE)
  }
  if (ncol(tax_tree) < 2) {
    stop("'tax_tree' must have at least 2 columns.", call. = FALSE)
  }

  # Filter to non-zero abundances
  community <- community[community > 0]
  species_names <- names(community)

  # Check species in taxonomy
  tax_species <- as.character(tax_tree[[1]])
  missing_sp <- setdiff(species_names, tax_species)
  if (length(missing_sp) > 0) {
    stop("Species not found in tax_tree: ",
         paste(missing_sp, collapse = ", "), call. = FALSE)
  }

  # Subset taxonomy to community species
  idx <- match(species_names, tax_species)
  tax_sub <- tax_tree[idx, , drop = FALSE]

  n_species <- length(community)
  n_levels <- ncol(tax_tree) - 1

  # --- If only one species, pTO = 0 ---
  if (n_species == 1) {
    return(list(
      uTO = 0, TO = 0, uTO_plus = 0, TO_plus = 0,
      Ed_levels = setNames(rep(0, n_levels + 1),
                           c("Species", names(tax_tree)[-1]))
    ))
  }

  # --- Helper: compute Deng entropy at all levels ---
  compute_deng_all_levels <- function(present_mask, tax_data, n_lev) {
    tax_present <- tax_data[present_mask, , drop = FALSE]
    n_present <- sum(present_mask)

    if (n_present <= 1) {
      ed <- setNames(rep(0, n_lev + 1),
                     c("Species", names(tax_data)[-1]))
      return(list(Ed = ed, active = integer(0)))
    }

    ed <- numeric(n_lev + 1)
    names(ed) <- c("Species", names(tax_data)[-1])
    ed[1] <- log(n_present)
    active <- 1L

    for (lev in seq_len(n_lev)) {
      col_idx <- lev + 1
      groups <- as.character(tax_present[[col_idx]])
      unique_groups <- unique(groups)
      n_nodes <- length(unique_groups)

      if (n_nodes <= 1) {
        ed[lev + 1] <- 0
        break
      }

      active <- c(active, as.integer(lev + 1))

      group_counts <- numeric(n_nodes)
      group_sizes <- integer(n_nodes)

      for (g in seq_along(unique_groups)) {
        mask <- groups == unique_groups[g]
        group_counts[g] <- sum(mask)
        group_sizes[g] <- sum(mask)
      }

      ed[lev + 1] <- deng_entropy_level(group_counts,
                                         group_sizes = group_sizes)
    }

    return(list(Ed = ed, active = active))
  }

  # --- Step 1: Compute Deng entropy at nk=0 (all species present) ---
  all_present <- rep(TRUE, n_species)
  result_nk0 <- compute_deng_all_levels(all_present, tax_sub, n_levels)
  Ed <- result_nk0$Ed
  active_levels <- result_nk0$active

  # --- Step 2: Compute the core product (pTO+) using nk=0 entropies ---
  Ed_S <- Ed[1]
  e_Ed_S_sq <- (exp(Ed_S))^2

  core_unweighted <- 1
  core_weighted <- 1

  for (lv in seq_along(active_levels)) {
    lev_idx <- active_levels[lv]
    Ed_i <- Ed[lev_idx]
    ratio <- e_Ed_S_sq / exp(Ed_i) + 1

    core_unweighted <- core_unweighted * (1 * ratio)

    w_i <- lev_idx
    core_weighted <- core_weighted * (w_i * ratio)
  }

  uTO_plus <- unname(log(core_unweighted))
  TO_plus <- unname(log(core_weighted))

  # --- Step 3: Slicing procedure for pTO (MACRO formula) ---
  # Key difference from ozkan_pto():
  #   - Max 9 steps (matching 9 TE sheets in the macro)
  #   - Only steps with >= 2 species are kept ("active" steps)
  #   - Weights based on n_active, not n_s
  max_abundance <- max(community)
  abundances <- as.numeric(community)
  max_steps <- 9L
  n_steps <- min(max_abundance, max_steps)

  products_u <- numeric(0)
  products_w <- numeric(0)

  for (step in seq_len(n_steps)) {
    nk <- step - 1

    present_mask <- abundances > nk
    n_present <- sum(present_mask)

    if (n_present <= 1) next

    tax_step <- tax_sub[present_mask, , drop = FALSE]
    result_step <- compute_deng_all_levels(
      rep(TRUE, n_present), tax_step, n_levels)
    Ed_step <- result_step$Ed
    active_step <- result_step$active

    Ed_S_step <- Ed_step[1]
    e_Ed_S_sq_step <- (exp(Ed_S_step))^2

    core_u_step <- 1
    core_w_step <- 1

    for (a in seq_along(active_step)) {
      lev_idx <- active_step[a]
      Ed_i_step <- Ed_step[lev_idx]
      ratio_step <- e_Ed_S_sq_step / exp(Ed_i_step) + 1

      core_u_step <- core_u_step * (1 * ratio_step)

      w_i <- lev_idx
      core_w_step <- core_w_step * (w_i * ratio_step)
    }

    products_u <- c(products_u, core_u_step)
    products_w <- c(products_w, core_w_step)
  }

  n_active <- length(products_u)

  if (n_active == 0) {
    uTO <- 0
    TO <- 0
  } else {
    weights_vec <- n_active:1
    denom <- sum(weights_vec)

    uTO <- log(sum(products_u * weights_vec) / denom)
    TO <- log(sum(products_w * weights_vec) / denom)
  }

  return(list(
    uTO = uTO,
    TO = TO,
    uTO_plus = uTO_plus,
    TO_plus = TO_plus,
    Ed_levels = Ed
  ))
}
